FROM python:3.9-slim

WORKDIR /app

COPY ./utils.py /app/utils.py
COPY ./Password_strength_checker.py /app/Password_strength_checker.py
COPY ./static /app/static

RUN pip install flask requests

EXPOSE 5003

ENV from_service=k8s

ENTRYPOINT ["python"]

CMD ["Password_strength_checker.py"]