FROM python:3.9-slim

WORKDIR /app

COPY ./utils.py /app/utils.py
COPY ./Common_password_checker.py /app/Common_password_checker.py
COPY ./static /app/static

RUN pip install flask requests

EXPOSE 5001

ENV from_service=k8s

ENTRYPOINT ["python"]

CMD ["Common_password_checker.py"]